"""added indexes

Revision ID: 133e631e19c5
Revises: cfb71b478c36
Create Date: 2024-05-16 08:53:32.238742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133e631e19c5'
down_revision = 'cfb71b478c36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_book_is_borrowed'), 'book', ['is_borrowed'], unique=False)
    op.create_unique_constraint(None, 'book', ['name'])
    op.create_index('idx_borrow_is_refunded_book_user', 'borrow', ['is_refunded', 'book_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_borrow_book_id'), 'borrow', ['book_id'], unique=False)
    op.create_index(op.f('ix_borrow_borrowed_date'), 'borrow', ['borrowed_date'], unique=False)
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_borrow_borrowed_date'), table_name='borrow')
    op.drop_index(op.f('ix_borrow_book_id'), table_name='borrow')
    op.drop_index('idx_borrow_is_refunded_book_user', table_name='borrow')
    op.drop_constraint(None, 'book', type_='unique')
    op.drop_index(op.f('ix_book_is_borrowed'), table_name='book')
    # ### end Alembic commands ###
