"""migration

Revision ID: 75859ac3a641
Revises: 
Create Date: 2024-05-16 06:26:09.071177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75859ac3a641'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
