version: '3'
services:
  app:
    build: .
    container_name: app
    command: python run.py
    volumes:
      - ./:/src
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - redis
    links:
      - db
  celery_worker:
    restart: unless-stopped
    build: .
    command: celery -A app worker --loglevel=info
    volumes:
      - ./:/src
    env_file:
      - .env
    depends_on:
      - app
      - redis
  celery_beat:
    restart: unless-stopped
    build: .
    command: celery -A app beat --loglevel=info
    volumes:
      - .:/src
    env_file:
      - .env
    depends_on:
      - app
      - redis
  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data/
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
volumes:
  data:

#version: '3'
#
#services:
#  db:
#    image: mariadb:10.5.9
#    restart: always
#    env_file:
#      - .env
#    volumes:
#      - ./db:/var/lib/mysql
#    ports:
#      - "3307:3306"
#  web:
#    build: ./
#    env_file:
#      - .env
#    volumes:
#      - ./..:/usr/src/app
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#      - redis
#  redis:
#    image: redis
#    restart: always
#    ports:
#      - "6379:6379"
#  celery_dashboard:
#    build: ./..
#    command: celery -A app.celery_utils flower --port:5555
#    env_file:
#      - .env
#    ports:
#      - 5555:5555
#    depends_on:
#      - web
#      - redis
#      # - worker
#  # worker:
#  #   build: ./..
#  #   command:  celery -A app.celery_utils worker --loglevel=info
#  #   env_file:
#  #     - .env
#  #   depends_on:
#  #     - web
#  #     - redis
#volumes:
#  db:
